<?php

namespace App\Command;

use App\Datafixture\FirstDataLoader;
use Doctrine\Common\DataFixtures\Loader;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Doctrine\Common\DataFixtures\Executor\ORMExecutor;
use Doctrine\Common\DataFixtures\Purger\ORMPurger;

#[AsCommand(name: 'app:load-fixtures')]
class LoadFixturesCommand extends Command
{
    #[\Override]
    protected function configure():void
    {
        $this->setDescription('Loads fixtures to the database.');
    }

    #[\Override]
    public function execute(InputInterface $input, OutputInterface $output): int
    {
        $loader = new Loader();
        $loader->addFixture(new FirstDataLoader());
        $executor = new ORMExecutor($GLOBALS['entityManager'], new ORMPurger());
        $executor->execute($loader->getFixtures());

        return Command::SUCCESS;
    }
    #[\Override]
    public function isEnabled(): bool
    {
        return parent::isEnabled(); // TODO: Change the autogenerated stub
    }
}