# docker-compose.yml
version: "3.9"
services:
  webapp:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_volume:/var/lib/mysql
      - ./docker/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: thedatabase
      MYSQL_USER: useradmin
      MYSQL_PASSWORD: S3cr3t

  adminer:
    image: adminer
    ports:
      - 8888:8080
    depends_on:
      - mysqldb

volumes:
  db_volume: