# Dockerfile.development
FROM php:7.4-apache

RUN docker-php-ext-install pdo pdo_mysql

# Setup Apache2 config

COPY docker/000-default.conf /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite

CMD ["apache2-foreground"]